base = [('Essa capinha de celular é muito boa', 'alegria'),
        ('este trabalho é agradável','alegria'),
        ('gosto de ficar no seu aconchego','alegria'),
        ('fiz a adesao ao curso hoje porque eu gostei','alegria'),
        ('eu sou admirada por muitos','alegria'),
        ('quero agradar meus filhos','alegria'),
        ('Gostei muito desta capinha de celular', 'alegria'),
        ('Capinha maravilhosa', 'alegria'),
        ('Que capinha bonita', 'alegria'),
        ('Abaixo do esperado', 'raiva'),
        ('Não gostei', 'raiva'),
        ('Desbotou na primeira semana', 'raiva'),
        ('Olha só essa capinha! ', 'alegria'),
        ('Material de baixa resistência', 'raiva'),
        ('que feia essa roupa','nojo'),
        ('da próxima vez, vou tentar sozinho','raiva'),
        ('este lugar continua assustador','medo'),
        ('só espero que não façam nenhum mal','medo'),
        ('socorro!, ele está fazendo a pior coisa','medo'),
        ('Essa é a pior coisa que eu já vi','medo'),
        ('que incomodo essa dor','nojo'),
        ('fico triste com o que aconteceu','tristeza'),
        ('que chato isso ter ocorrido','tristeza'),
        ('não acredito nisso!','tristeza'),
        ('não acredito no que fez','tristeza'),
        ('patife, bandido, canalha','raiva'),
        ('odeio aquele bosta','raiva'),
        ('meteu um chifre','raiva'),
        ('colocou um chifre','raiva'),
        ('traiu mais uma vez','nojo'),
        ('não da para confiar','medo'),
        ('está abusando da paciência','raiva'),
        ('não abuse da minha paciência','raiva'),
        ('não faça isso','medo'),
        ('eu quero mesmo é que ele faça isso','raiva'),
        ('desejo que ele traia ela','raiva'),
        ('estou torcendo para ele se dar mal','raiva'),
        ('trair foi uma escolha ruim','nojo'),
        ('eu odeio esse cara, espero que saia logo','raiva'),
        ('estou torcendo para que dê tudo errado','raiva'),
        ('ele é um cafajeste, traidor','raiva'),
        ('o cara é muito tóxico, é um lixo','nojo'),
        ('macho toxico','raiva'),
        ('eu sinto nojo desse cara','nojo'),
        ('não acredito que escolheram ele','medo'),
        ('não acredito','medo'),
        ('não da pra acreditar','medo'),
        ('eca, que coisa mais asquerosa','nojo'),
        ('já podemos eliminar o fulano?','raiva'),
        ('estou esperando para ver se ele vai trair a fulana','nojo'),
        ('torcendo para ele botar mais um chifre nela','raiva'),
        ('Custo benefício excelente', 'alegria'),
        ('A foto é diferente do produto', 'raiva'), 
        ('espero que ele não faça isso','medo'),
        ('🤮','nojo'),
        ('🤢','nojo'),
        ('😞','nojo'),
        ('😒','nojo'),
        ('🙄','nojo'),
        ('😟','tristeza'),
        ('😠','raiva'),
        ('😕','tristeza'),
        ('🙁','tristeza'),
        ('☹','tristeza'),
        ('😩','tristeza'),
        ('😨','tristeza'),
        ('😦','tristeza'),
        ('😢','tristeza'),
        ('😪','nojo'),
        ('😭','tristeza'),
        ('🤦‍♀️','nojo'),
        ('🤦','nojo'),
        ('🤦‍♂️','nojo'),
        ('🙍‍♀️','tristeza'),
        ('🙍','tristeza'),
        ('🙍‍♂️','tristeza'),
        ('💔','tristeza'),
        ('😡','raiva'),
        ('🤬','raiva'),
        ('😂','alegria'),
        ('😅','alegria'),
        ('🤣','alegria'),
        ('😀','alegria'),
        ('😃','alegria'),
        ('💩','nojo'),
        ('💕','alegria'),
        ('💞','alegria'),
        ('💓','alegria'),
        ('💖','alegria'),
        ('💟','alegria'),
        ('😰','tristeza'),
        ('😨','tristeza'),
        ('😢','tristeza'),
        ('😥','tristeza'),
        ('🥶','medo'),
        ('👿','raiva'),
        ('👏','alegria'),
        ('🙌','alegria'),
        ('👍','alegria'),
        ('👋','medo'),
        ('✨','alegria')]