base = [
        ('eu sou admirada por muitos','alegria'),
        ('Custo benefício excelente', 'alegria'),
        ('quero agradar meus filhos','alegria'),
        ('Gostei muito desta capinha de celular', 'alegria'),
        ('Olha só essa capinha! ', 'alegria'),
        ('este lugar continua assustador','medo'),
        ('não acredito que escolheram ele','medo'),
        ('socorro!, ele está fazendo a pior coisa','medo'),
        ('Essa é a pior coisa que eu já vi','medo'),
        ('não acredito','medo'),
        ('não da para confiar','medo'),
        ('não acredito nisso!','tristeza'),
        ('não acredito no que fez','tristeza'),
        ('eu sinto nojo desse cara','nojo'),
        ('detesto esse perfil de pessoa','nojo'),
        ('tenho nojo da sujeira dele', 'nojo'),
        ('vontade de vomitar','nojo'),
        ('o cara é muito tóxico, é um lixo','nojo'),
        ('estou esperando para ver se ele vai trair a fulana','nojo'),
        ('macho toxico','raiva'),
        ('torcendo para ele botar mais um chifre nela','raiva'),
        ('A foto é diferente do produto', 'raiva'), 
        ('😂','alegria'),
        ('💖','alegria'),
        ('💟','alegria'),
        ('😟','tristeza'),
        ('😨','tristeza'),
        ('😦','tristeza'),
        ('😢','tristeza'),
        ('🙍‍♀️','tristeza'),
        ('🙍','tristeza'),
        ('🙍‍♂️','tristeza'),
        ('💔','tristeza'),
        ('😭','tristeza'),
        ('🤮','nojo'),
        ('🤦‍♂️','nojo'),
        ('😡','raiva'),
        ('👿','raiva'),
        ('😠','raiva'),
        ('🤬','raiva'),
        ('🥶','medo'),
        ('👋','medo')
]